### PR TITLE
refactor(category-sort): refactor category-sort implementation

### PR DESCRIPTION
**Pull request by hisabimbola**
Hey @junajan 

I tried to refactor the category test

Please take a look, if the implementation works

### CODE REVIEW

**Comment by hisabimbola** [comment]
Any update on this @junajan

**Comment by junajan** [comment]
@hisabimbola - to sort an array of N items - you have to do at least N * Log(N) steps (and comparations) so if we want to fix this implementation (which does only N steps when looping through CSV rows) we have to add another loop which will use for example binary search algorithm and find the best position in an output array.

**Comment by hisabimbola** [comment]
I don't quite follow what you mean...

Leaving all the computer science stuff behind for now, does this work? cover your scenarios/test cases? if not let me know and we try to fix it or we close this PR

Cc @Siilwyn

**Comment by Siilwyn** [comment]
Guess that's a "no" looking at the last commits, @hisabimbola

**Comment by hisabimbola** [comment]
Yeah, it's a No 😞, probably if I have more time to work on it later I will love to see if there's a way around it.

**Pull request closed without merging**
