### PR TITLE
can use an OAuth access token

### PR DESCRIPTION
**Pull request by yanns**
@hajoeichler @emmenko please review
import and export tested locally with an OAuth token

### CODE REVIEW

**Comment by hajoeichler** [comment]
:+1:

**Comment by yanns** [comment]
The build is successful with node 0.12 but failed with node 0.10: https://travis-ci.org/sphereio/sphere-category-sync/builds/85108020. Can somebody help here?

**Comment by emmenko** [comment]
@yanns no idea :(

**Comment by emmenko** [comment]
@yanns I tried locally with node 10 and it seems to work, not sure what the problem is...

```bash
emmenko: ~/dev/src/sphere-category-sync (use_access_token *)
$ cucumber -t ~@wip features/export.feature
Feature: Export categories

  Scenario: Error on wrong template file                                      # features/export.feature:3
    When I run `category-sync -p nicola export -t not_here.csv -o output.csv` # aruba-0.7.4/lib/aruba/cucumber.rb:119
    Then the exit status should be 1                                          # aruba-0.7.4/lib/aruba/cucumber.rb:223
    And the output should contain "Error: ENOENT, open 'not_here.csv'"        # aruba-0.7.4/lib/aruba/cucumber.rb:166

1 scenario (1 passed)
3 steps (3 passed)
0m0.632s
emmenko: ~/dev/src/sphere-category-sync (use_access_token *)
$ node -v
v0.10.38
emmenko: ~/dev/src/sphere-category-sync (use_access_token *)
$ ruby -v
ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
```

**Comment by yanns** [comment]
yes really strange

**Comment by yanns** [comment]
thx for testing!

**Comment by yanns** [comment]
@emmenko https://github.com/sphereio/sphere-category-sync/commit/409e55de09a602f2979d034bc106508b8735a39a ;)

**Pull request merged**
